/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Calculadora;

/**
 *
 * @author PC
 */
public class CalculadoraInterfaz extends javax.swing.JFrame {

    private String cadenaNumeros = "";
    private String operacion = "nula";
    private double primerNumero, resultado;
    private boolean activado = true;
    private boolean punto = true;
    
    public CalculadoraInterfaz() {
        initComponents();
        this.setTitle("Calculadora");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonC = new javax.swing.JButton();
        BotonSIN = new javax.swing.JButton();
        BotonCOS = new javax.swing.JButton();
        BotonTAN = new javax.swing.JButton();
        BotonIVA = new javax.swing.JButton();
        BotonPOW = new javax.swing.JButton();
        BotonRAIZ = new javax.swing.JButton();
        BotonDIV = new javax.swing.JButton();
        Boton7 = new javax.swing.JButton();
        Boton8 = new javax.swing.JButton();
        Boton9 = new javax.swing.JButton();
        BotonMUL = new javax.swing.JButton();
        Boton4 = new javax.swing.JButton();
        Boton5 = new javax.swing.JButton();
        Boton6 = new javax.swing.JButton();
        BotonRES = new javax.swing.JButton();
        Boton1 = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();
        Boton3 = new javax.swing.JButton();
        BotonSUM = new javax.swing.JButton();
        BotonPN = new javax.swing.JButton();
        Boton0 = new javax.swing.JButton();
        BotonPUNTO = new javax.swing.JButton();
        BotonIGUAL = new javax.swing.JButton();
        NumeroPantalla = new javax.swing.JLabel();
        MuestraPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(6, 4));

        BotonC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonC.setText("C");
        BotonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCActionPerformed(evt);
            }
        });
        jPanel1.add(BotonC);

        BotonSIN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonSIN.setText("SIN");
        BotonSIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSINActionPerformed(evt);
            }
        });
        jPanel1.add(BotonSIN);

        BotonCOS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonCOS.setText("COS");
        BotonCOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCOSActionPerformed(evt);
            }
        });
        jPanel1.add(BotonCOS);

        BotonTAN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonTAN.setText("TAN");
        BotonTAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTANActionPerformed(evt);
            }
        });
        jPanel1.add(BotonTAN);

        BotonIVA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonIVA.setText("IVA%");
        BotonIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIVAActionPerformed(evt);
            }
        });
        jPanel1.add(BotonIVA);

        BotonPOW.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonPOW.setText("^");
        BotonPOW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPOWActionPerformed(evt);
            }
        });
        jPanel1.add(BotonPOW);

        BotonRAIZ.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonRAIZ.setText("√");
        BotonRAIZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRAIZActionPerformed(evt);
            }
        });
        jPanel1.add(BotonRAIZ);

        BotonDIV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonDIV.setText("/");
        BotonDIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDIVActionPerformed(evt);
            }
        });
        jPanel1.add(BotonDIV);

        Boton7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Boton7.setText("7");
        Boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton7ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton7);

        Boton8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Boton8.setText("8");
        Boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton8ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton8);

        Boton9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Boton9.setText("9");
        Boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton9ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton9);

        BotonMUL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonMUL.setText("X");
        BotonMUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMULActionPerformed(evt);
            }
        });
        jPanel1.add(BotonMUL);

        Boton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Boton4.setText("4");
        Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton4ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton4);

        Boton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Boton5.setText("5");
        Boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton5ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton5);

        Boton6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Boton6.setText("6");
        Boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton6ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton6);

        BotonRES.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonRES.setText("-");
        BotonRES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRESActionPerformed(evt);
            }
        });
        jPanel1.add(BotonRES);

        Boton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Boton1.setText("1");
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton1);

        Boton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Boton2.setText("2");
        Boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton2);

        Boton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Boton3.setText("3");
        Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton3ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton3);

        BotonSUM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonSUM.setText("+");
        BotonSUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSUMActionPerformed(evt);
            }
        });
        jPanel1.add(BotonSUM);

        BotonPN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonPN.setText("+/-");
        BotonPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPNActionPerformed(evt);
            }
        });
        jPanel1.add(BotonPN);

        Boton0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Boton0.setText("0");
        Boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton0ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton0);

        BotonPUNTO.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonPUNTO.setText(".");
        BotonPUNTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPUNTOActionPerformed(evt);
            }
        });
        jPanel1.add(BotonPUNTO);

        BotonIGUAL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonIGUAL.setText("=");
        BotonIGUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIGUALActionPerformed(evt);
            }
        });
        jPanel1.add(BotonIGUAL);

        NumeroPantalla.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        NumeroPantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NumeroPantalla.setText("0");

        MuestraPantalla.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MuestraPantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MuestraPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NumeroPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MuestraPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumeroPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCActionPerformed
        MuestraPantalla.setText("");
        NumeroPantalla.setText("0");
        operacion = "nula";
        activado = true;
        punto = true;
    }//GEN-LAST:event_BotonCActionPerformed

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        if(NumeroPantalla.getText().equals("0")){
            cadenaNumeros = "1";
        }else{
            cadenaNumeros += "1";
        }
        NumeroPantalla.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_Boton1ActionPerformed

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        if(NumeroPantalla.getText().equals("0")){
            cadenaNumeros = "2";
        }else{
            cadenaNumeros += "2";
        }
        NumeroPantalla.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_Boton2ActionPerformed

    private void Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton3ActionPerformed
        if(NumeroPantalla.getText().equals("0")){
            cadenaNumeros = "3";
        }else{
            cadenaNumeros += "3";
        }
        NumeroPantalla.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_Boton3ActionPerformed

    private void Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton4ActionPerformed
        if(NumeroPantalla.getText().equals("0")){
            cadenaNumeros = "4";
        }else{
            cadenaNumeros += "4";
        }
        NumeroPantalla.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_Boton4ActionPerformed

    private void Boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton5ActionPerformed
        if(NumeroPantalla.getText().equals("0")){
            cadenaNumeros = "5";
        }else{
            cadenaNumeros += "5";
        }
        NumeroPantalla.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_Boton5ActionPerformed

    private void Boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton6ActionPerformed
        if(NumeroPantalla.getText().equals("0")){
            cadenaNumeros = "6";
        }else{
            cadenaNumeros += "6";
        }
        NumeroPantalla.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_Boton6ActionPerformed

    private void Boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton7ActionPerformed
        if(NumeroPantalla.getText().equals("0")){
            cadenaNumeros = "7";
        }else{
            cadenaNumeros += "7";
        }
        NumeroPantalla.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_Boton7ActionPerformed

    private void Boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton8ActionPerformed
        if(NumeroPantalla.getText().equals("0")){
            cadenaNumeros = "8";
        }else{
            cadenaNumeros += "8";
        }
        NumeroPantalla.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_Boton8ActionPerformed

    private void Boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton9ActionPerformed
        if(NumeroPantalla.getText().equals("0")){
            cadenaNumeros = "9";
        }else{
            cadenaNumeros += "9";
        }
        NumeroPantalla.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_Boton9ActionPerformed

    private void Boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton0ActionPerformed
        if(NumeroPantalla.getText().equals("0")){
            cadenaNumeros = "0";
        }else{
            cadenaNumeros += "0";
        }
        NumeroPantalla.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_Boton0ActionPerformed

    private void BotonSUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSUMActionPerformed
        if(activado == true){
            primerNumero = Double.parseDouble(cadenaNumeros);
            MuestraPantalla.setText(cadenaNumeros + " + ");
            cadenaNumeros = "";
            operacion = "sumar";
            
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_BotonSUMActionPerformed

    private void BotonIGUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIGUALActionPerformed
        double segundoNumero;
        if(operacion.equals("nula")){
            NumeroPantalla.setText(cadenaNumeros);
        }
        else if(operacion.equals("sumar")){
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero + segundoNumero;
            NumeroPantalla.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
        }else if(operacion.equals("restar")){
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero - segundoNumero;
            NumeroPantalla.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
        }else if(operacion.equals("multiplicar")){
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero * segundoNumero;
            NumeroPantalla.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
        }else if(operacion.equals("dividir")){
            segundoNumero = Double.parseDouble(cadenaNumeros);
            if(segundoNumero == 0){
                NumeroPantalla.setText("Error Zero");
            }else{
                resultado = primerNumero / segundoNumero;
                NumeroPantalla.setText(String.format("% .2f", resultado));
                cadenaNumeros = String.valueOf(resultado);
                operacion = "nula";
            }          
        }else if(operacion.equals("porcentaje")){
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero * (1 + segundoNumero / 100);
            NumeroPantalla.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
        }else if(operacion.equals("raiz")){
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = Math.pow(primerNumero, 1.0 / segundoNumero);
            NumeroPantalla.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
        }else if(operacion.equals("potencia")){
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = Math.pow(primerNumero, segundoNumero);
            NumeroPantalla.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
        }
        MuestraPantalla.setText("");
        activado = true;
    }//GEN-LAST:event_BotonIGUALActionPerformed

    private void BotonMULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMULActionPerformed
        if(activado == true){
            primerNumero = Double.parseDouble(cadenaNumeros);
            MuestraPantalla.setText(cadenaNumeros + " x ");
            cadenaNumeros = "";
            operacion = "multiplicar";
            
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_BotonMULActionPerformed

    private void BotonRESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRESActionPerformed
        if(activado == true){
            primerNumero = Double.parseDouble(cadenaNumeros);
            MuestraPantalla.setText(cadenaNumeros + " - ");
            cadenaNumeros = "";
            operacion = "restar";
            
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_BotonRESActionPerformed

    private void BotonDIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDIVActionPerformed
        if(activado == true){
            primerNumero = Double.parseDouble(cadenaNumeros);
            MuestraPantalla.setText(cadenaNumeros + " / ");
            cadenaNumeros = "";
            operacion = "dividir";
            
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_BotonDIVActionPerformed

    private void BotonRAIZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRAIZActionPerformed
        if(activado == true){
            primerNumero = Double.parseDouble(cadenaNumeros);
            MuestraPantalla.setText(" √ " + cadenaNumeros);
            cadenaNumeros = "";
            operacion = "raiz";
            
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_BotonRAIZActionPerformed

    private void BotonPOWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPOWActionPerformed
        primerNumero = Double.parseDouble(cadenaNumeros);
            MuestraPantalla.setText(cadenaNumeros + " ^ ");
            cadenaNumeros = "";
            operacion = "potencia";
            
            activado = false;
            punto = true;
    }//GEN-LAST:event_BotonPOWActionPerformed

    private void BotonSINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSINActionPerformed
        primerNumero = Double.parseDouble(cadenaNumeros);
        MuestraPantalla.setText("Sin("+ cadenaNumeros +")");
        resultado = Math.sin(primerNumero);
        NumeroPantalla.setText(String.format("%.2f", resultado));
        cadenaNumeros = String.valueOf(resultado);
        punto = true;
    }//GEN-LAST:event_BotonSINActionPerformed

    private void BotonCOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCOSActionPerformed
        primerNumero = Double.parseDouble(cadenaNumeros);
        MuestraPantalla.setText("Cos("+ cadenaNumeros +")");
        resultado = Math.cos(primerNumero);
        NumeroPantalla.setText(String.format("%.2f", resultado));
        cadenaNumeros = String.valueOf(resultado);
        punto = true;
    }//GEN-LAST:event_BotonCOSActionPerformed

    private void BotonTANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTANActionPerformed
        primerNumero = Double.parseDouble(cadenaNumeros);
        MuestraPantalla.setText("Tan("+ cadenaNumeros +")");
        resultado = Math.tan(primerNumero);
        NumeroPantalla.setText(String.format("%.2f", resultado));
        cadenaNumeros = String.valueOf(resultado);
        punto = true;
    }//GEN-LAST:event_BotonTANActionPerformed

    private void BotonPUNTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPUNTOActionPerformed
        if(punto == true){
            if(cadenaNumeros.equals("")){
                cadenaNumeros = "0.";
            }else{
                cadenaNumeros += ".";                
            }
            NumeroPantalla.setText(cadenaNumeros);
            punto = false;
        }
        
    }//GEN-LAST:event_BotonPUNTOActionPerformed

    private void BotonPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPNActionPerformed
        if(cadenaNumeros.charAt(0) != '-'){
            cadenaNumeros = "-" + cadenaNumeros;
        }else{
            cadenaNumeros = cadenaNumeros.substring(1,cadenaNumeros.length());
        }
        NumeroPantalla.setText(cadenaNumeros);
    }//GEN-LAST:event_BotonPNActionPerformed

    private void BotonIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIVAActionPerformed
        if(activado == true){
            primerNumero = Double.parseDouble(cadenaNumeros);
            MuestraPantalla.setText(cadenaNumeros + " IVA% ");
            cadenaNumeros = "";
            operacion = "porcentaje";
            
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_BotonIVAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton0;
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton2;
    private javax.swing.JButton Boton3;
    private javax.swing.JButton Boton4;
    private javax.swing.JButton Boton5;
    private javax.swing.JButton Boton6;
    private javax.swing.JButton Boton7;
    private javax.swing.JButton Boton8;
    private javax.swing.JButton Boton9;
    private javax.swing.JButton BotonC;
    private javax.swing.JButton BotonCOS;
    private javax.swing.JButton BotonDIV;
    private javax.swing.JButton BotonIGUAL;
    private javax.swing.JButton BotonIVA;
    private javax.swing.JButton BotonMUL;
    private javax.swing.JButton BotonPN;
    private javax.swing.JButton BotonPOW;
    private javax.swing.JButton BotonPUNTO;
    private javax.swing.JButton BotonRAIZ;
    private javax.swing.JButton BotonRES;
    private javax.swing.JButton BotonSIN;
    private javax.swing.JButton BotonSUM;
    private javax.swing.JButton BotonTAN;
    private javax.swing.JLabel MuestraPantalla;
    private javax.swing.JLabel NumeroPantalla;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
